export GCP_REPO=tap
export GCP_PROJECT=project
export GCP_REGION=europe-west3
export GCP_CLUSTER=cluster_name

export IMGPKG_REGISTRY_HOSTNAME_0=registry.tanzu.vmware.com
export IMGPKG_REGISTRY_USERNAME_0=
export IMGPKG_REGISTRY_PASSWORD_0=''
export TAP_VERSION='1.5.3'
export BUILDSERVICE_VERSION='1.10.10'
export INSTALL_REPO=$GCP_PROJECT/$GCP_REPO
export INSTALL_REGISTRY_HOSTNAME=$GCP_REGION-docker.pkg.dev
export INSTALL_REGISTRY_USERNAME=_json_key_base64
export INSTALL_REGISTRY_PASSWORD=$(base64 -i -w 0 ./tap-sa_key.json)
export CLUSTER_ESSENTIALS_BUNDLE_SHA=sha256:61385f946a94a663f846223c3365c790b7d0ff13378789c2c2003192d2b154e9
export INSTALL_BUNDLE=$INSTALL_REGISTRY_HOSTNAME/$INSTALL_REPO/cluster-essentials-bundle@$CLUSTER_ESSENTIALS_BUNDLE_SHA